"""Synthetic questions and expected evidence used by retrieval evaluations."""

evaluation_cases = [
    # Baseline Supported (5 cases)
    {
        "id": "rag_001",
        "category": "baseline_supported",
        "question": "What vector database does Harshu AI OS use?",
        "answerable": True,
        "expected_evidence": "Chroma",
    },
    {
        "id": "rag_002",
        "category": "baseline_supported",
        "question": "Which API framework does Harshu AI OS use?",
        "answerable": True,
        "expected_evidence": "FastAPI",
    },
    {
        "id": "rag_003",
        "category": "baseline_supported",
        "question": "How does Harshu AI OS handle simple user queries?",
        "answerable": True,
        "expected_evidence": "router",
    },
    {
        "id": "rag_004",
        "category": "baseline_supported",
        "question": "What library validates request payloads in Harshu AI OS?",
        "answerable": True,
        "expected_evidence": "Pydantic",
    },
    {
        "id": "rag_005",
        "category": "baseline_supported",
        "question": "What component supplies grounded context to the language model in Harshu AI OS?",
        "answerable": True,
        "expected_evidence": "RAG",
    },
    # Baseline Unsupported (2 cases)
    {
        "id": "rag_006",
        "category": "baseline_unsupported",
        "question": "Which payment gateway does Harshu AI OS use?",
        "answerable": False,
        "expected_evidence": None,
    },
    {
        "id": "rag_007",
        "category": "baseline_unsupported",
        "question": "Which Kubernetes cluster hosts Harshu AI OS?",
        "answerable": False,
        "expected_evidence": None,
    },
    # Supported Paraphrases (5 cases)
    {
        "id": "rag_008",
        "category": "supported_paraphrase",
        "question": "Which database is responsible for storing text embeddings in Harshu AI OS?",
        "answerable": True,
        "expected_evidence": "ChromaDB",
    },
    {
        "id": "rag_009",
        "category": "supported_paraphrase",
        "question": "What web framework powers the HTTP endpoints of Harshu AI OS?",
        "answerable": True,
        "expected_evidence": "FastAPI",
    },
    {
        "id": "rag_010",
        "category": "supported_paraphrase",
        "question": "Name one fast lightweight model used for simple queries to reduce latency and cost.",
        "answerable": True,
        "expected_evidence": "Gemini Flash",
    },
    {
        "id": "rag_011",
        "category": "supported_paraphrase",
        "question": "Which library verifies the structure of API request payloads?",
        "answerable": True,
        "expected_evidence": "Pydantic",
    },
    {
        "id": "rag_012",
        "category": "supported_paraphrase",
        "question": "What technique pulls relevant document passages before calling the model?",
        "answerable": True,
        "expected_evidence": "Retrieval-Augmented Generation",
    },
    # Difficult Supported (5 cases)
    {
        "id": "rag_013",
        "category": "difficult_supported",
        "question": "What three categories does the intelligent query router sort incoming prompts into?",
        "answerable": True,
        "expected_evidence": "simple, general, or complex",
    },
    {
        "id": "rag_014",
        "category": "difficult_supported",
        "question": "What values does the system compute to rank retrieved chunks by relevance?",
        "answerable": True,
        "expected_evidence": "similarity distances",
    },
    {
        "id": "rag_015",
        "category": "difficult_supported",
        "question": "What module tests RAG performance by comparing retrieved chunks against expected answers?",
        "answerable": True,
        "expected_evidence": "retrieval evaluation",
    },
    {
        "id": "rag_016",
        "category": "difficult_supported",
        "question": "Why are simple queries routed specifically to Gemini Flash?",
        "answerable": True,
        "expected_evidence": "minimize latency and cost",
    },
    {
        "id": "rag_017",
        "category": "difficult_supported",
        "question": "What generates vector embeddings from document text in Harshu AI OS?",
        "answerable": True,
        "expected_evidence": "embedding model",
    },
    # Unsupported (4 cases)
    {
        "id": "rag_018",
        "category": "unsupported",
        "question": "What relational database stores user account profiles in Harshu AI OS?",
        "answerable": False,
        "expected_evidence": None,
    },
    {
        "id": "rag_019",
        "category": "unsupported",
        "question": "Which OAuth2 provider handles user login and authentication?",
        "answerable": False,
        "expected_evidence": None,
    },
    {
        "id": "rag_020",
        "category": "unsupported",
        "question": "What Docker base image is used to containerize Harshu AI OS?",
        "answerable": False,
        "expected_evidence": None,
    },
    {
        "id": "rag_021",
        "category": "unsupported",
        "question": "Which Redis instance is used for caching prompt responses?",
        "answerable": False,
        "expected_evidence": None,
    },
    # Misleading Near-Match (4 cases)
    {
        "id": "rag_022",
        "category": "misleading_near_match",
        "question": "Does ChromaDB automatically handle user password hashing in Harshu AI OS?",
        "answerable": False,
        "expected_evidence": None,
    },
    {
        "id": "rag_023",
        "category": "misleading_near_match",
        "question": "Which FastAPI endpoint exports monthly billing invoices as PDF?",
        "answerable": False,
        "expected_evidence": None,
    },
    {
        "id": "rag_024",
        "category": "misleading_near_match",
        "question": "How does Pydantic automatically train new embedding models in Harshu AI OS?",
        "answerable": False,
        "expected_evidence": None,
    },
    {
        "id": "rag_025",
        "category": "misleading_near_match",
        "question": "Does Gemini Flash manage the local HNSW vector index directly?",
        "answerable": False,
        "expected_evidence": None,
    },
]
